spring.application.name=Lima
# JWT Configuration
jwt.secret=${JWT_KEY}
KING.secretkey=${KING_KEY}
KNIGHT.secretkey= ${KNIGHT_KEY}
QUEEN.secretkey=${QUEEN_KEY}

# PostgreSQL Database Configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:password}
spring.datasource.driver-class-name=org.postgresql.Driver


# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Connection Pool Configuration
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=5

server.port=8080
#server.address=0.0.0.0

#FireBase config
#app.firebase-configuration-file=${FIREBASE_KEY}
app.firebase-configuration-file=classpath:lima-74d3d-firebase-adminsdk-fbsvc-cdb3580656.json

